name: PyGeoMechanical CI

on:
  push:
    branches: [ main]

  pull_request:
    branches: [ main ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  testing:
    name: Testing
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pygm_testing
          environment-file: environment.yml
          python-version: 3.9
          channels: conda-forge
      - name: Run tests with pytest
        run: |
          pytest
    
      - name: Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}